exports.ukCities = [
  "Please select city",
  "London",
  "Birmingham",
  "Manchester",
  "Liverpool",
  "Portsmouth",
  "Southampton",
  "Nottingham",
  "Bristol",
  "Leicester",
  "Coventry",
  "Belfast",
  "Stockport",
  "Bradford",
  "Plymouth",
  "Derby",
  "Westminster",
  "Wolverhampton",
  "Norwich",
  "Luton",
  "Solihull",
  "Islington",
  "Aberdeen",
  "Croydon",
  "Bournemouth",
  "Basildon",
  "Ilford",
  "Warrington",
  "Kingswood",
  "Oxford",
  "Harrow",
  "West Bromwich",
  "Gloucester",
  "Blackpool",
  "Sale",
  "Tottenham",
  "Cambridge",
  "Romford",
  "Colchester",
  "High Wycombe",
  "Gateshead",
  "Slough",
  "Blackburn",
  "Chelmsford",
  "Rochdale",
  "Rotherham",
  "Walthamstow",
  "Maidstone",
  "Basingstoke",
  "Salford",
  "Hounslow",
  "Wembley",
  "Worcester",
  "Hammersmith",
  "Rayleigh",
  "Hemel Hempstead",
  "Bath",
  "Darlington",
  "Hove",
  "Hastings",
  "Watford",
  "Stevenage",
  "Hartlepool",
  "Chester",
  "Fulham",
  "Nuneaton",
  "Ealing",
  "Hayes",
  "Aylesbury",
  "Edmonton",
  "Saint Albans",
  "Burnley",
  "Batley",
  "Scunthorpe",
  "Dudley",
  "Brixton",
  "Paisley",
  "Chatham",
  "Edgware",
  "East Ham",
  "Weston-super-Mare",
  "Carlisle",
  "South Shields",
  "East Kilbride",
  "Burton upon Trent",
  "Harrogate",
  "Crewe",
  "Lowestoft",
  "Rugby",
  "Chingford",
  "Uxbridge",
  "Southall",
  "Walsall",
  "Grays",
  "Walton upon Thames",
  "Thornton Heath",
  "Finchley",
  "Kensington",
  "Boston",
  "Paignton",
  "Waterlooville",
  "Hornchurch",
  "Merthyr Tudful",
  "Mitcham",
  "Feltham",
  "Stourbridge",
  "Hereford",
  "Rochester",
  "Dewsbury",
  "Acton",
  "Twickenham",
  "Scarborough",
  "Wrecsam",
  "Wandsworth",
  "Ellesmere Port",
  "Bangor",
  "Taunton",
  "Loughborough",
  "Barking",
  "Littlehampton",
  "Ruislip",
  "Streatham",
  "Royal Tunbridge Wells",
  "Bebington",
  "Barrow in Furness",
  "Macclesfield",
  "Wellingborough",
  "Kettering",
  "Braintree",
  "Royal Leamington Spa",
  "Dunfermline",
  "Altrincham",
  "Lancaster",
  "Crosby",
  "Barri",
  "Bootle",
  "Stratford",
  "Folkestone",
  "Cumbernauld",
  "Andover",
  "Neath",
  "Rowley Regis",
  "Leith",
  "Yeovil",
  "Eltham",
  "Sutton in Ashfield",
  "Morden",
  "Barnet",
  "West Bridgford",
  "Stretford",
  "Beckenham",
  "Greenford",
  "Cheshunt",
  "Salisbury",
  "Ashton",
  "Surbiton",
  "Catford",
  "Worksop",
  "Morley",
  "Middleton",
  "Fleet",
  "Fareham",
  "Urmston",
  "Sutton",
  "Caerphilly",
  "Bridgwater",
  "Newbury",
  "Welling",
  "Kirkby",
  "Ramsgate",
  "Castleford",
  "Strood",
  "Cleethorpes",
  "Ilkeston",
  "Chorley",
  "Herne Bay",
  "Bishops Stortford",
  "Arnold",
  "Coalville",
  "Bletchley",
  "Leighton Buzzard",
  "Airdrie",
  "Blyth",
  "Laindon",
  "Llanelli",
  "Bicester",
  "Beeston",
  "Small Heath",
  "Whitley Bay",
  "Denton",
  "Falkirk",
  "Walkden",
  "Kenton",
  "Bridlington",
  "Billingham",
  "Dunstable",
  "Spalding",
  "Grantham",
  "North Shields",
  "Colwyn Bay",
  "Hitchin",
  "Rainham",
  "Wickford",
  "Letchworth",
  "Huyton",
  "Abingdon",
  "Trowbridge",
  "Wigston Magna",
  "Didcot",
  "Earley",
  "Borehamwood",
  "Bexleyheath",
  "Prestwich",
  "Ecclesfield",
  "Darwen",
  "Pontypridd",
  "Rutherglen",
  "Saint Neots",
  "Pinner",
  "Dover",
  "Chichester",
  "Deal",
  "Northolt",
  "Wishaw",
  "Carshalton",
  "Bulwell",
  "Kendal",
  "Cramlington",
  "Bromsgrove",
  "Pont-y-pŵl",
  "Hanwell",
  "Hertford",
  "Frome",
  "Wood Green",
  "Daventry",
  "Darlaston",
  "Ashington",
  "Longton",
  "Melton Mowbray",
  "Aldridge",
  "Farnworth",
  "Highbury",
  "Newton Aycliffe",
  "Cheadle Hulme",
  "Bournville",
  "Shenley Brook End",
  "Consett",
  "Northfield",
  "Coulsdon",
  "Bilston",
  "Wellington",
  "Bishop Auckland",
  "Longbridge",
  "Bloxwich",
  "Upminster",
  "Rhyl",
  "Droitwich",
  "Hindley",
  "Westhoughton",
  "Ryde",
  "Gorleston-on-Sea",
  "Thornaby on Tees",
  "Kings Norton",
  "Plymstock",
  "Barnstaple",
  "Arbroath",
  "Caversham",
  "Oadby",
  "Stalybridge",
  "Stanmore",
  "Droylsden",
  "Perry Barr",
  "Gosforth",
  "Whitefield",
  "Penwortham",
  "Harborne",
  "Swinton",
  "Market Harborough",
  "Erdington",
  "Clifton",
  "Stratton Saint Margaret",
  "Wednesfield",
  "Farsley",
  "Guiseley",
  "March",
  "Tiverton",
  "Litherland",
  "Acomb",
  "Newton in Makerfield",
  "Penarth",
  "Camborne",
  "Newquay",
  "Northwood",
  "Atherton",
  "Belper",
  "Sheldon",
  "Yate",
  "Bailleston",
  "Truro",
  "Chandlers Ford",
  "Royton",
  "Clevedon",
  "Dronfield",
  "Ossett",
  "Woodlesford",
  "Wallington",
  "Norton",
  "Leek",
  "Leigh-on-Sea",
  "Boscombe",
  "Failsworth",
  "Kirkstall",
  "Maesteg",
  "Shoreham-by-Sea",
  "Hythe",
  "Maghull",
  "Rothwell",
  "Seaham",
  "Peterlee",
  "Killingworth",
  "Horwich",
  "Bispham",
  "Biddulph",
  "Stoke Gifford",
  "Selby",
  "Stamford",
  "Davyhulme",
  "Burnham-on-Sea",
  "Abbots Langley",
  "Great Linford",
  "Dukinfield",
  "Peterhead",
  "Ecclesall",
  "Hebburn",
  "Frimley",
  "Molesey",
  "Prestatyn",
  "Calne",
  "Southbourne",
  "Broughty Ferry",
  "Bedlington",
  "Hadleigh",
  "Bingley",
  "Warminster",
  "Redhill",
  "Bourne",
  "Colne",
  "Tonypandy",
  "Moreton",
  "Fern Down",
  "Bonnyrigg",
  "Quedgeley",
  "Houghton Regis",
  "Friern Barnet",
  "Milton",
  "Cottingham",
  "Clitheroe",
  "Heckmondwike",
  "Clayton",
  "High Blantyre",
  "Maltby",
  "Haslingden",
  "Devizes",
  "Fazakerley",
  "Connahs Quay",
  "Plumstead",
  "Wellington",
  "Whickham",
  "Keynsham",
  "Cleckheaton",
  "Cowley",
  "Enfield Lock",
  "Kilwinning",
  "Westbury",
  "Stepney",
  "Basford",
  "Brackley",
  "Tyldesley",
  "East Barnet",
  "Upton",
  "Johnstone",
  "Worcester Park",
  "South Hayling",
  "Addlestone",
  "Royston",
  "Buckley",
  "Porthcawl",
  "Nailsea",
  "West Ham",
  "Shipley",
  "Baildon",
  "Wombwell",
  "Llantrisant",
  "Hazel Grove",
  "Dawlish",
  "Bidston",
  "Verwood",
  "Palmers Green",
  "New Brighton",
  "Netherton",
  "Hessle",
  "Kew Green",
  "West Wickham",
  "Bromborough",
  "Baguley",
  "Balham",
  "Larkhall",
  "Prestwick",
  "Melksham",
  "Wibsey",
  "Lowton",
  "Moston",
  "Thornbury",
  "Deysbrook",
  "Armthorpe",
  "Southgate",
  "Dollis Hill",
  "West Derby",
  "West Drayton",
  "Rottingdean",
  "Kidbrooke",
  "Rock Ferry",
  "Shirley",
  "Patcham",
  "Seacroft",
  "Maldon",
  "Leyton",
  "Hythe",
  "Childwall",
  "Nantwich",
  "Marlow",
  "Pemberton",
  "Brierley Hill",
  "Rustington",
  "Cosham",
  "Rosyth",
  "Kidlington",
  "Whitby",
  "Rossington",
  "Hilsea",
  "Clifton",
  "Little Hulton",
  "Chaddesden",
  "Amblecote",
  "Egg Buckland",
  "Shiremoor",
  "Shirebrook",
  "West Boldon",
  "Linlithgow",
  "Dingle",
  "Walsall Wood",
  "Fraserburgh",
  "Caerfyrddin",
  "Wollaston",
  "Chard",
  "Goodmayes",
  "Pendlebury",
  "Holborn",
  "Midsomer Norton",
  "Gornalwood",
  "Yiewsley",
  "Shenley Church End",
  "Leagrave",
  "Buckingham",
  "Milngavie",
  "Brownhills",
  "Hornsey",
  "Sutton on Hull",
  "Wolverton",
  "Barton upon Irwell",
  "Blunsdon Saint Andrew",
  "Coseley",
  "Ovenden",
  "Chepstow",
  "Lye",
  "Giffnock",
  "Thatto Heath",
  "Sedgley",
  "Minehead",
  "Snaresbrook",
  "Sandown",
  "Hoyland Nether",
  "Hackney",
  "Wallingford",
  "Belgrave",
  "Wanstead",
  "Blundellsands",
  "Brislington",
  "Culcheth",
  "Sandridge",
  "Holyhead",
  "Haydock",
  "Wealdstone",
  "Harrow Weald",
  "Carnoustie",
  "Burslem",
  "Mountain Ash",
  "Castle Bromwich",
  "Linslade",
  "Prescot",
  "Eckington",
  "Aylestone",
  "Southborough",
  "Timperley",
  "Bottesford",
  "Cudworth",
  "Oakham",
  "Highgate",
  "Hollinwood",
  "Earlestown",
  "Flixton",
  "Parkstone",
  "Royston",
  "Ormesby",
  "Hatch End",
  "Ryhope",
  "Holbeach",
  "Eccleston",
  "Bradford-on-Avon",
  "Gourock",
  "Stranraer",
  "Spitalfields",
  "Cheam",
  "Lemington",
  "New Silksworth",
  "Forres",
  "Lydney",
  "Marton",
  "Bishopstoke",
  "Aberaman",
  "Birchington",
  "Nairn",
  "Handsworth",
  "Liskeard",
  "Stocksbridge",
  "Kippax",
  "Tottington",
  "Whitchurch",
  "Helston",
  "Raynes Park",
  "Lambeth",
  "Killamarsh",
  "Thames Ditton",
  "Horsell",
  "Broadwater",
  "Wilnecote",
  "Tilehurst",
  "Aberbargoed",
  "Littleport",
  "Dunbar",
  "Barwell",
  "Cupar",
  "Broughton Astley",
  "Partick",
  "Ifield",
  "Cowley",
  "Clayton le Moors",
  "Cam",
  "Blackwood",
  "Great Billing",
  "Seaton",
  "Birtley",
  "Glascote",
  "Mountsorrel",
  "Brierfield",
  "Heybridge",
  "New Bilton",
  "Exhall",
  "Newbold",
  "Cross Gates",
  "Stony Stratford",
  "Rothwell",
  "Rhôs-on-Sea",
  "Stonehouse",
  "Sundon",
  "Codsall",
  "Attleborough",
  "Hucknall under Huthwaite",
  "Pyle",
  "Harefield",
  "Wickersley",
  "Greenhill",
  "Roby",
  "Lee-on-the-Solent",
  "Kirkham",
  "Frampton Cotterell",
  "Faringdon",
  "Allington",
  "Saint Peters",
  "Shifnal",
  "Crewkerne",
  "Westgate on Sea",
  "Warrenpoint",
  "Dowlais",
  "Duntocher",
  "Thornhill",
  "Gedling",
  "Bolton upon Dearne",
  "Godmanchester",
  "Aintree",
  "Pakefield",
  "Whetstone",
  "Cove",
  "Bilton",
  "Bothwell",
  "Uddingston",
  "Long Ditton",
  "Alcester",
  "Handforth",
  "Shephall",
  "Dyce",
  "Hollington",
  "Llantwit Fardre",
  "Long Ashton",
  "Highbridge",
  "Withernsea",
  "Porth",
  "Great Burstead",
  "Saltburn-by-the-Sea",
  "Honley",
  "Govan",
  "Cheddar",
  "Broughton",
  "Littlemore",
  "Kirk Ella",
  "Wadsley",
  "Leavesden Green",
  "Lexden",
  "Utley",
  "Bridge of Allan",
  "Bishopton",
  "Paulton",
  "Wincanton",
  "Church",
  "Great Meols",
  "Harleston",
  "Harlescott",
  "Ottery Saint Mary",
  "Loughor",
  "North Woolwich",
  "Huntington",
  "Coedpoeth",
  "Somerton",
  "Eton",
  "Old Kilpatrick",
  "Kirby Muxloe",
  "Histon",
  "Tillicoultry",
  "Nelson",
  "Alva",
  "Ingatestone",
  "Lees",
  "Kingsthorpe",
  "Cowpen",
  "Wilford",
  "Seaton Delaval",
  "Ferndale",
  "Grenoside",
  "Beddau",
  "Banff",
  "Bare",
  "Chasetown",
  "Deanshanger",
  "Tayport",
  "Anstruther",
  "Walton le Dale",
  "Watchet",
  "Highcliffe",
  "Kilburn",
  "Llanharan",
  "Llanbadarn-fawr",
  "Menai Bridge",
  "Sherborne Saint John",
  "Clackmannan",
  "Swalwell",
  "Stainton",
  "Harton",
  "Kinghorn",
  "Appledore",
  "New Earswick",
  "Bushbury",
];

exports.usStates = [
  "Please select city",
  "Alabama",
  "Alaska",
  "American Samoa",
  "Arizona",
  "Arkansas",
  "California",
  "Colorado",
  "Connecticut",
  "Delaware",
  "District of Columbia",
  "Federated States of Micronesia",
  "Florida",
  "Georgia",
  "Guam",
  "Hawaii",
  "Idaho",
  "Illinois",
  "Indiana",
  "Iowa",
  "Kansas",
  "Kentucky",
  "Louisiana",
  "Maine",
  "Marshall Islands",
  "Maryland",
  "Massachusetts",
  "Michigan",
  "Minnesota",
  "Mississippi",
  "Missouri",
  "Montana",
  "Nebraska",
  "Nevada",
  "New Hampshire",
  "New Jersey",
  "New Mexico",
  "New York",
  "North Carolina",
  "North Dakota",
  "Northern Mariana Islands",
  "Ohio",
  "Oklahoma",
  "Oregon",
  "Palau",
  "Pennsylvania",
  "Puerto Rico",
  "Rhode Island",
  "South Carolina",
  "South Dakota",
  "Tennessee",
  "Texas",
  "Utah",
  "Vermont",
  "Virgin Island",
  "Virginia",
  "Washington",
  "West Virginia",
  "Wisconsin",
  "Wyoming",
];

exports.pkCities = [
  "Please select city",
  "Islamabad",
  "Ahmed Nager",
  "Ahmadpur East",
  "Ali Khan",
  "Alipur",
  "Arifwala",
  "Attock",
  "Bhera",
  "Bhalwal",
  "Bahawalnagar",
  "Bahawalpur",
  "Bhakkar",
  "Burewala",
  "Chillianwala",
  "Chakwal",
  "Chichawatni",
  "Chiniot",
  "Chishtian",
  "Daska",
  "Darya Khan",
  "Dera Ghazi",
  "Dhaular",
  "Dina",
  "Dinga",
  "Dipalpur",
  "Faisalabad",
  "Fateh Jhang",
  "Ghakhar Mandi",
  "Gojra",
  "Gujranwala",
  "Gujrat",
  "Gujar Khan",
  "Hafizabad",
  "Haroonabad",
  "Hasilpur",
  "Haveli",
  "Lakha",
  "Jalalpur",
  "Jattan",
  "Jampur",
  "Jaranwala",
  "Jhang",
  "Jhelum",
  "Kalabagh",
  "Karor Lal",
  "Kasur",
  "Kamalia",
  "Kamoke",
  "Khanewal",
  "Khanpur",
  "Kharian",
  "Khushab",
  "Kot Adu",
  "Jauharabad",
  "Lahore",
  "Lalamusa",
  "Layyah",
  "Liaquat Pur",
  "Lodhran",
  "Malakwal",
  "Mamoori",
  "Mailsi",
  "Mandi Bahauddin",
  "mian Channu",
  "Mianwali",
  "Multan",
  "Murree",
  "Muridke",
  "Mianwali Bangla",
  "Muzaffargarh",
  "Narowal",
  "Okara",
  "Renala Khurd",
  "Pakpattan",
  "Pattoki",
  "Pir Mahal",
  "Qaimpur",
  "Qila Didar",
  "Rabwah",
  "Raiwind",
  "Rajanpur",
  "Rahim Yar",
  "Rawalpindi",
  "Sadiqabad",
  "Safdarabad",
  "Sahiwal",
  "Sangla Hill",
  "Sarai Alamgir",
  "Sargodha",
  "Shakargarh",
  "Sheikhupura",
  "Sialkot",
  "Sohawa",
  "Soianwala",
  "Siranwali",
  "Talagang",
  "Taxila",
  "Toba Tek",
  "Vehari",
  "Wah Cantonment",
  "Wazirabad",
  "Badin",
  "Bhirkan",
  "Rajo Khanani",
  "Chak",
  "Dadu",
  "Digri",
  "Diplo",
  "Dokri",
  "Ghotki",
  "Haala",
  "Hyderabad",
  "Islamkot",
  "Jacobabad",
  "Jamshoro",
  "Jungshahi",
  "Kandhkot",
  "Kandiaro",
  "Karachi",
  "Kashmore",
  "Keti Bandar",
  "Khairpur",
  "Kotri",
  "Larkana",
  "Matiari",
  "Mehar",
  "Mirpur Khas",
  "Mithani",
  "Mithi",
  "Mehrabpur",
  "Moro",
  "Nagarparkar",
  "Naudero",
  "Naushahro Feroze",
  "Naushara",
  "Nawabshah",
  "Nazimabad",
  "Qambar",
  "Qasimabad",
  "Ranipur",
  "Ratodero",
  "Rohri",
  "Sakrand",
  "Sanghar",
  "Shahbandar",
  "Shahdadkot",
  "Shahdadpur",
  "Shahpur Chakar",
  "Shikarpaur",
  "Sukkur",
  "Tangwani",
  "Tando Adam",
  "Tando Allahyar",
  "Tando Muhammad",
  "Thatta",
  "Umerkot",
  "Warah",
  "Abbottabad",
  "Adezai",
  "Alpuri",
  "Akora Khattak",
  "Ayubia",
  "Banda Daud",
  "Bannu",
  "Batkhela",
  "Battagram",
  "Birote",
  "Chakdara",
  "Charsadda",
  "Chitral",
  "Daggar",
  "Dargai",
  "Darya Khan",
  "dera Ismail",
  "Doaba",
  "Dir",
  "Drosh",
  "Hangu",
  "Haripur",
  "Karak",
  "Kohat",
  "Kulachi",
  "Lakki Marwat",
  "Latamber",
  "Madyan",
  "Mansehra",
  "Mardan",
  "Mastuj",
  "Mingora",
  "Nowshera",
  "Paharpur",
  "Pabbi",
  "Peshawar",
  "Saidu Sharif",
  "Shorkot",
  "Shewa Adda",
  "Swabi",
  "Swat",
  "Tangi",
  "Tank",
  "Thall",
  "Timergara",
  "Tordher",
  "Awaran",
  "Barkhan",
  "Chagai",
  "Dera Bugti",
  "Gwadar",
  "Harnai",
  "Jafarabad",
  "Jhal Magsi",
  "Kacchi",
  "Kalat",
  "Kech",
  "Kharan",
  "Khuzdar",
  "Killa Abdullah",
  "Killa Saifullah",
  "Kohlu",
  "Lasbela",
  "Lehri",
  "Loralai",
  "Mastung",
  "Musakhel",
  "Nasirabad",
  "Nushki",
  "Panjgur",
  "Pishin valley",
  "Quetta",
  "Sherani",
  "Sibi",
  "Sohbatpur",
  "Washuk",
  "Zhob",
  "Ziarat",
];
